### ISSUE TITLE
Require config.paths to be set at the application level.

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/bedrock#10]
It's difficult to guess reasonable defaults for the `config.paths` values.  Computed config defaults could be used that throw an error if the values are unset.  This would force applications to set the values to something sane for their environment.

**Comment by davidlehn** [comment]
Deprecation warnings added.  Change to throw errors for v2.0.0.

**Comment by mattcollier** [comment]
@davidlehn can this be closed.

**Comment by davidlehn** [comment]
@mattcollier Looks like this was never fully resolved.  Warnings are issued in `lib/bedrock.js`, but we forgot to address the comments about switching to errors and leaped past a 2.0.0 and 3.0.0 release.  I think the reasoning here still stands and those warnings and arbitrary defaults should perhaps be removed in favor of errors when paths are not set somewhere else.  It's a quick change, but a breaking one, which is why the comments are there about doing this for 2.0.0.

**Comment by dlongley** [comment]
Closing this, moved it to ensure override feature.
