### ISSUE TITLE
Consider removal of `winston-mail` dependency

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock#101]
The `mail` transport in the Bedrock logging framework has not seen usage in recent years.

The `winston-mail` module has not had a release in approximately 3 years.  The maintainers are not keeping up with dependency updates.

https://github.com/wavded/winston-mail/commits/master

Specifically, the package is still using `emailjs@2` while `emailjs@4` is the current release:

https://github.com/eleith/emailjs/commits/main

The `emailjs@2` dependency graph includes a version of the `ramda` module which has a ReDoS vulnerability:
https://security.snyk.io/vuln/SNYK-JS-RAMDA-1582370

I propose that the `mail` transport be removed along with the `winston-mail` dependency.

**Comment by dlongley** [comment]
I'd be very happy to see this go -- and I would have removed it earlier when we went to 5.x if I had known it wasn't used. @davidlehn -- is it true we don't use this at all?

**Comment by davidlehn** [comment]
I don't think we have anything currently actively using it.  I think that was added long ago mainly as a critical error warning fallback for monolith applications.  But we, and others, are all trending to other system designs now.   It looks like it would be easy to add back to an application if needed as either a new bedrock module or just a few bits of app level code.  So I'm guessing removing it would be fine.

**Comment by dlongley** [comment]
@mattcollier,

If we're going to require a major breaking change for this -- I'd like us to figure out if there is anything else that should be removed at the same time to save on churn. Breaking here requires every package to be updated.

I'm ok with removing this unused and disabled by default feature without a major breaking change since we just recently released 5.x.

**Comment by dlongley** [comment]
Addressed by #102.

**Comment by dlongley** [comment]
Closing, removed in v6.
