### ISSUE TITLE
Master channel closed on exit

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock#13]
When the master process is exiting, we attempt to notify workers of this fact but the master channel has already closed. In node 4+, these messages will never be sent and an uncaught error is thrown as a result. We should remove this `exit` listener as it now serves no purpose. Instead, we should only send these messages prior to the master exiting. For example, when a worker suicides, the master process will exit, but it should wait until it has sent these messages to any workers that are still connected.

Also, while we're fixing this bug, note that `worker.suicide` has been deprecated and replaced with `worker.exitedAfterDisconnect`. See: https://nodejs.org/api/cluster.html#cluster_worker_suicide

**Comment by dlongley** [comment]
Note: This bug can be seen by running bedrock-views' `compile-less` command when the number of workers is set to something higher than 1.

**Comment by mattcollier** [comment]
This is no longer applicable.
