### ISSUE TITLE
Refactor package design to allow easier updates.

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/bedrock#35]
While adding `uuid` and `delay` helpers to core `bedrock`, the issue of maintenance of bedrock came up.
https://github.com/digitalbazaar/bedrock/pull/34
https://github.com/digitalbazaar/bedrock/pull/34#issuecomment-474156586

Currently it is very difficult to do any type of semver major updates to bedrock itself.  Such a version bump could potentially require every package that depends on bedrock to be updated at once.  This has become intractable due to the number of direct and indirect dependents.  For many classes of changes this may just be benign version compatibility warnings, but if an actual API change were to be made, it would be difficult, maybe impossible, to just use that updated version from one package.  The recent changes involve adding helpers to bedrock.  While convenient they do add more complexity into versioning and managing the exported API.

We should explore alternate package design methods that may help mitigate this issue.  I imagine there are tradeoffs between ease of use and maintainability issues.

**Comment by mattcollier** [comment]
I think we have consensus that we won't be adding any additional utils to bedrock until we get this sorted.

**Comment by mattcollier** [comment]
We have removed test framework and jsonld from bedrock in efforts to address this issue.  Future additions to the utilis collection will be discussed at length I'm sure, closing this.
