### ISSUE TITLE
Remove non-operational `ran` variable and parameter.

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock#38]
https://github.com/digitalbazaar/bedrock/blob/master/lib/bedrock.js#L218

This variable is declared, but never changed, and therefore the feature it was intended to provide is  not and has not been working.  Rather than fix the deprecated implementation, the `ran` variable should just be removed.

**Comment by dlongley** [comment]
@mattcollier actually, let's not remove it, it *is* functional and could be used in the old version. You could check it for `ran === false` vs. `ran === undefined`. Let's just deprecate the old version and leave it be.
