### ISSUE TITLE
Add `initContext` helper

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock#40]
Now that a browser/node compatible structure for context modules has been found, it would be good to have a robust helper to initialize context modules.

The implementation here can be a starting place: https://github.com/digitalbazaar/bedrock-security-context/pull/2

Here's some ideas from @davidlehn in response to the bedrock-security-context PR

> It's going to be repeated in any bedrock-*-context package.
> If for some reason this package wasn't a peer dep everywhere, and two packages with different versions were used, this may cause incorrect initialization. Putting in checks for such issues would be better in a bedrock common API call.
> This assumes a one to one mapping of every constants entry with contexts entries. Two loops could address that.

**Comment by dlongley** [comment]
If we're creating a helper to manage whether or not certain constants have been set -- then it sounds like it's more generic than for "contexts". We should make sure that if we create a feature like this that it either only makes sense when using "contexts" or that the feature is more broadly applicable to other things.

**Comment by mattcollier** [comment]
@dlongley what do you mean by 'only makes sense when using "contexts"'?  For my part, I'm mainly interested in a convenience method that does the right thing without having to copy a bunch of boilerplate in bedrock-foo-context modules.  something like `initContextPackage('npm-package-name')` seems like it would be nice.

**Comment by dlongley** [comment]
@mattcollier, is there something special about context packages? What would the new feature *do* specifically -- and could that be applied to the benefit of other packages that are not specifically about contexts?

**Comment by mattcollier** [comment]
This is what the present implementation does:
```
const {config: {constants: bedrockConstants}} = require('bedrock');
const {contexts, constants: contextConstants} = require('security-context');

for(const c in contextConstants) {
  const contextUrl = contextConstants[c];
  bedrockConstants[c] = contextUrl;
  bedrockConstants.CONTEXTS[contextUrl] = contexts.get(contextUrl);
}
```

**Comment by dlongley** [comment]
I'm apprehensive about further strongly binding bedrock core to jsonld. I'd rather us move in a direction where jsonld was an optional package and it could be upgraded independently. I think we should also consider how all of this would work with the better designed document loader we haven't gotten around to creating yet.

**Comment by mattcollier** [comment]
jsonld is being removed from bedrock@2.
