### ISSUE TITLE
Add minimum workers option.

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/bedrock#43]
An option could be added so that an application can enforce a minimum number of workers. 
 If an application wants at least 2 workers then the current method to scale by setting `config.core.workers` to `0` would not work on a 1 core host.  A `minWorkers` could fix that.  Alternatively, an application could just set this manually like `config.core.workers = Math.max(os.cpus().length, 2)`.

**Comment by dlongley** [comment]
Closing as we have a mechanism for doing this already with computed config or static JS as mentioned in the OP.
