### ISSUE TITLE
Errors thrown in async event handers are not logged in bedrock logs

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock#44]
If any of the handlers for a bedrock.* event throw an error, an `UnhandledPromiseRejectionWarning` error is logged to the console, but is not logged in the bedrock logs.  This makes diagnosing problems on deployments where the server is running as a service difficult.

Sample error: https://gist.github.com/mattcollier/07cdc9b07cb6b5e75d72c94cb6c612fa

It would be good to capture these errors and put them in the logs.

**Comment by aljones15** [comment]
unHandledPromise Reject has been a problem for awhile and Node actually was/is scheduled to include these errors at some point. in the mean time unHandledPromiseReject is an event that can be listened for:
https://medium.com/dailyjs/how-to-prevent-your-node-js-process-from-crashing-5d40247b8ab2

```
process.on('unhandledRejection', (reason, promise) => {
  console.log('Unhandled Rejection at:', reason.stack || reason)
  // Recommended: send the information to sentry.io
  // or whatever crash reporting service you use
})
```

**Comment by dlongley** [comment]
I suspect this code could use some modernizing with async/await so it would be more robust:

https://github.com/digitalbazaar/async-node-events/blob/master/lib/async-node-events.js#L18-L63

... and that might even be where the rejected promise is escaping.

**Comment by aljones15** [comment]
@dlongley not argument that we need to fix said code, but better error catching will help us identify where that error happens hence asking for permission to add a listener for unhandled exceptions to each worker, logger will log the pid and error so we can also identify inside which process the error happens.

**Comment by mattcollier** [comment]
Would it be possible to wrap some units of code in a try/catch block until a more comprehensive solution is found?

**Comment by mattcollier** [comment]
@davidlehn I think work was done on this?  Also I think Node 14 brought some additional tools in dealing with this.  Can this be closed?

**Comment by dlongley** [comment]
This is handled now.
