### ISSUE TITLE
Update `runOnceAsync` to match the behavior or `runOnce`

### ISSUE THREAD

**Issue by gannan08** [digitalbazaar/bedrock#45]
The current implementation of `runOnceAsync` requires a developer to create extra logic to ensure that the job ran once and other workers wait for its completion. This is not desired. The function should handle this logic internally to match the behavior as `runOnce`, namely all workers should wait until the job is done. Additionally, tests should be added to highlight this behavior.

**Comment by dlongley** [comment]
These lines:

```js
process.removeListener('bedrock.runOnce', runOnce);
```
https://github.com/digitalbazaar/bedrock/blob/master/lib/bedrock.js#L225

```js
process.removeListener('bedrock.runOnceAsync', _runOnce);
```
https://github.com/digitalbazaar/bedrock/blob/master/lib/bedrock.js#L286

Look like typos to me. They should read:

```js
process.removeListener('message', _runOnce);
```

Right now those process listeners are never being removed.

**Comment by aljones15** [comment]
I think switching from using on to addListener might also help as we use removeListener to remove the listener.

**Comment by mattcollier** [comment]
Issues around the `runOnce` API have been resolved.
