### ISSUE TITLE
`runOnce` and `runOnceAsync` doesn't handle circular JSON

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock#47]
Messages sent (particularly errors thrown with express request objects that have cycles) are problematic -- and they need to be flattened before sent via IPC.

**Comment by mattcollier** [comment]
I believe this has been addressed.  @dlongley @davidlehn

**Comment by davidlehn** [comment]
I think it may be ok?  There is a `decycle` call in there for errors.  Is there some case that doesn't handle?

And to be pedantic, JSON can't be circular. ;-)
