### ISSUE TITLE
Separate test.js and test framework into bedrock-test

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock#51]
Since we're eyeing up a breaking release of bedrock, I think it would be good to split out the test framework, moving it into bedrock-test or some other module?

One issue that would be good to address is that the `bedrock.started` event is never makes it to top level apps when running test suites because the test suite is the first listener on on that event: https://github.com/digitalbazaar/bedrock/blob/5a46f2894e952ed0433b4aa6335d95763d754dc1/lib/test.js#L66-L67

This is problematic when attempting to do testing in the ledger stack in particular which makes use of the `bedrock.started` event to initialize ledgers.

If the listener for running the test suite is registered last, when we require `bedrock-test`, then I think we would be better off.

**Comment by dlongley** [comment]
+1

**Comment by mattcollier** [comment]
Addressed in https://github.com/digitalbazaar/bedrock/pull/52

**Comment by mattcollier** [comment]
This has landed.
