### ISSUE TITLE
Add option to handle errors from start().

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/bedrock#56]
3.x is returning a promise from `start()` that can result in unhandled exception errors unless the promise is accounted for.  It seems like this API is fine, as it allows users to handle errors as appropriate in their app, but does result in a bit more code.  A possible solution would be to add a config option that would control catching internal errors, and perhaps `console.error` them.

**Comment by mattcollier** [comment]
Look like this was linked to a merged PR.  @davidlehn can this be closed?

**Comment by davidlehn** [comment]
This had been left open on purpose to track a potential feature.  Idea was maybe to add code to handle `start()` errors by default.  But that hasn't happened yet.  Should we close such things?  We could label them with "help wanted" "enhancement" or something.  Or it could just be closed, as there's nothing actually wrong, just the API could just be easier to use.  Is a code TODO better?

**Comment by davidlehn** [comment]
I'm reopening this since I think it should still be addressed somehow.  I just now ran into unhandled errors in bedrock-mongodb test suite.  Something to avoid needing patches like this would be good:
```diff
- bedrock.start();
+ bedrock.start().catch(err => console.error(err));
```

**Comment by dlongley** [comment]
This is handled now. Unhandled promise rejections get caught and the process exits -- and app creators may optionally handle errors thrown by `bedrock.start()` if desired.
