### ISSUE TITLE
Implement clean shutdown code via bedrock.exit()

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock#60]
We need to implement cleaner shutdown code via `bedrock.exit()`. When `bedrock.exit()` is called, a `bedrock.exit` event should be emitted that is awaited on all workers -- and new workers should be prevented from starting up. Once all workers have exited, we can call cluster kill. A flag can be provided to `bedrock.exit()` with an optional timeout that will forcibly call cluster kill after the timeout.

**Comment by aljones15** [comment]
this sounds good. I will work on this when time allows.

**Comment by aljones15** [comment]
one idea is to make a new function in `bedrock.utils` cancellable:

```js

bedrock.utils.cancellable = ({events = [], action}) => new Promise(async (resolve, reject) => {
  for(const event of events) {
    // we could make this configurable to also call on resolve
    bedrock.on(event, () => reject(new Error(`Action cancelled by event ${event}`)));
  }
  const result = await action();
  resolve(result);
});
```

This is meta-code and does not handle situations such as wanting to cancel with a reject for some events and a resolve for others, but it would allow:

```js

const {cancellable}} = bedrock.utls;
const FireForgetCancel = await cancellable({events: ['event'], action: watchMongo});
```

This would allow async functions that might be running on `exit` to cancel and remove themselves from the async que.

**Comment by aljones15** [comment]
`AbortController` which is experimental in node 15 could also be used to handle cancellation:

https://developer.mozilla.org/en-US/docs/Web/API/AbortController

**Comment by dlongley** [comment]
We now emit the `bedrock.exit` event and apps can handle it and gracefully exit.
