### ISSUE TITLE
Consider updating Winston logger

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock#62]
Winston@1 is getting long in the tooth, the project is at v3

https://github.com/winstonjs/winston/blob/master/CHANGELOG.md

**Comment by davidlehn** [comment]
When I last looked into this there was some reason it wasn't a trivial update.  I'm forgetting the details.  Likely related to the scary clustering aggregation logging code.  It would also be good to see if there are more modern approaches that would simplify that code.

**Comment by aljones15** [comment]
@mattcollier can this be closed now?

**Comment by mattcollier** [comment]
@aljones15 correct, thanks for pointing it out. This landed: https://github.com/digitalbazaar/bedrock/blob/master/CHANGELOG.md#400---2020-12-07
