### ISSUE TITLE
`_runWorker` should catch rejected promises and exit

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock#69]

**Comment by davidlehn** [comment]
Is this somehow related to https://github.com/digitalbazaar/bedrock/issues/56 or did you want workers to specifically exit?

**Comment by aljones15** [comment]
pretty confident this is common knowledge, but there is a node event that occurs:

```js
process.on('unhandledRejection', error => {
  // Will print "unhandledRejection err is not defined"
  console.log('unhandledRejection', error.message);
});
```

so this would be pretty easy to do and also we could throw a logger in for the unhandledRejection too.

**Comment by dlongley** [comment]
This is handled now.
