### ISSUE TITLE
Use rfdc module as bedrock.util.clone implementation

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock#70]
Replace lodash.clone with https://www.npmjs.com/package/rfdc

https://www.npmjs.com/package/rfdc#benchmarks

We will get a free performance bump wherever bedrock.util.clone is used.

**Comment by dlongley** [comment]
This might be better: https://github.com/lukeed/klona

**Comment by dlongley** [comment]
Instead, we should remove `bedrock.util.clone` and any other utility function as well, so that changes / fixes / removals in the core bedrock package do not disrupt all other dependencies.

**Comment by dlongley** [comment]
`bedrock.util.clone` is being removed in v6, closing.
