### ISSUE TITLE
Fix SIGTERM handling

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock#85]
This branch demonstrates the issue:

https://github.com/digitalbazaar/bedrock/compare/create-sigterm

Our deployment infrastructures sends a SIGTERM when it wants to shut down applications.  I was not seeing proper shutdown logging so I started investigating.

What we have now seems to work nicely with SIGINT, but SIGTERM is not hitting the event handlers we have for the purpose.  I show that a handler outside the `_runWorker` function does see and SIGTERM event.

Symlink this branch to the app of your choice and use `htop` or similar to send SIGTERM to the bedrock worker.

**Comment by dlongley** [comment]
Addressed by #86.
