### ISSUE TITLE
Bedrock is not properly reporting exit code 1 on test failure

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock#94]
https://github.com/digitalbazaar/bedrock/compare/evergreen-tests?expand=1

Successful CI action reported there, but there was indeed a test failure shown here:

https://github.com/digitalbazaar/bedrock/runs/4451334012?check_suite_focus=true

Inspect the 'Run test with Node.js 14.x' section.

This was evidently broken by the recent signal handlers patch released in v4.4.2:
https://github.com/digitalbazaar/bedrock/blob/main/CHANGELOG.md#442---2021-11-04

If the bad test is applied to v4.4.1 return code of 1 is properly returned and CI properly reflects a failure:
https://github.com/digitalbazaar/bedrock/compare/4.4.1-bad-test?expand=1

The improper `0` return code can also be seen by doing.  A `1` is expected when the test suite fails.
```
npm test
echo $?
```

**Comment by dlongley** [comment]
Addressed by #95.
