### ISSUE TITLE
Use new `node:` URLs where applicable?

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock#96]
This feature landed in Node 14.13.1

[EDIT] in 14.180+ this syntax can also be used with `require()`.

https://nodejs.org/api/esm.html#node-imports

https://2ality.com/2021/12/node-protocol-imports.html
https://github.com/nodejs/node/issues/38343
https://github.com/nodejs/node/pull/37246
https://github.com/nodejs/node/pull/35387

Among other things, this is in support of "a more extensive standard library in JavaScript" that will eventually be put into the `node:` namespace and allows the re-use of existing NPM package names without conflicts.
https://github.com/tc39/proposal-built-in-modules

**Comment by davidlehn** [comment]
In case this should be enforced, even with an option for `require`:
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-node-protocol.md

There are probably other things in that library too.  I wanted to use the module checks as well:
https://github.com/digitalbazaar/eslint-config-digitalbazaar/pull/55

**Comment by dlongley** [comment]
v6 uses `node:` imports.
